### ISSUE TITLE
Caddy in production

### ISSUE THREAD

**Issue by DenBeke** [caddy-book/awesome-caddy#2]
Does this blogpost fit in somewhere?

https://denbeke.be/blog/servers/two-months-ago-i-started-to-serve-the-web-like-its-2016-and-im-still-loving-caddy-migrating-from-nginx-to-caddy-server/

**Comment by humboldtux** [comment]
I've added you blog post to the list.

And i added you as admin of this repo as well, Mathias.

Feel free to contribute as you like.

**Comment by DenBeke** [comment]
Thanks!
